### PR TITLE
try to add configurable path

### PR DESCRIPTION
**Pull request by quentindemetz**

### CODE REVIEW

**Comment by siegy22** [comment]
Is there any particular reason why you don't add wkhtmltopdf in your `$PATH`?

**Comment by quentindemetz** [comment]
I am using EmlToPdf on Heroku.
I have chosen to install wkhtmltopdf with https://github.com/rposborne/wkhtmltopdf-heroku which provides the relevant wkhtmltopdf binary. FYI this gem [already configures other PDF-related gems.](https://github.com/rposborne/wkhtmltopdf-heroku/blob/master/lib/wkhtmltopdf-heroku.rb)

The binary is installed in 
```
irb(main)> Gem.bin_path('wkhtmltopdf-heroku', 'wkhtmltopdf-linux-amd64')
=> "/app/vendor/bundle/ruby/2.6.0/gems/wkhtmltopdf-heroku-2.12.5.0/bin/"
```
This path will change if the gem is bumped or if I change ruby versions. Which is why I think it's more future-proof to be able to define the path in my application's initializer.

**Comment by siegy22** [comment]
I recommend using/building a heroku buildpack which installs `wkhtmltox` binaries. E.g. https://elements.heroku.com/buildpacks/simplefractal/heroku-buildpack-wkhtmltopdf

**Comment by quentindemetz** [comment]
I didn't know about this buildpack, thank you for the reference, from what I can see:
- it isn't tested on the latest heroku stack (18)
- the gem uses a later (minor) version (0.12.5 vs 0.12.4)

Is there an issue with keeping this option open (similarly to other pdf-related libraries) ?

**Comment by siegy22** [comment]
I'm going to have a look at the CI, but I like the change! 
Thanks for your contribution

**Pull request merged**
